steps:
  # 0. CloudBuild 경로 확인
  - name: 'alpine'
    args: ['sh', '-c', 'ls -l ']


  # 1. 도커 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',   
      '-t', 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/$REPO_NAME/cloudbuild-test:$SHORT_SHA', 'CloudBuild/']
    id : 'build'

  # 2. Prisma Cloud Image Scan
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'run'
    - '--rm'
    - '-v'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - 'asia-northeast3-docker.pkg.dev/flash-physics-368407/twistlock/twistlock:latest'
    - 'images'
    - 'scan'
    - '--address'
    - 'https://asia-northeast1.cloud.twistlock.com/japan-1167212692'
    - '--user'
    - 'f255704b-1edd-444c-b46d-38346976b03c'
    - '--password'
    - 'd4l97POej0I7IfYYm01m9SH3krw='
    - '--details'
    - 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/$REPO_NAME/hello-world-nodejs:$SHORT_SHA'

  # 2. Artifact Registry에 푸시하는 단계
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/$REPO_NAME/cloudbuild-test:$SHORT_SHA' ]
    id : 'push'

            
  # 3. Cloud Run 동작
  # - name: 'gcr.io/cloud-builders/gcloud'
  # - script: |
  #     gcloud run deploy changtalk-run --image us-west1-docker.pkg.dev/quixotic-skill-402605/test/${tag}/test --region us-west2 --platform managed --allow-unauthenticated



options:
  logging: CLOUD_LOGGING_ONLY
