



  steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/bash'
  args: ['-c', 'ls -R CloudBuild']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 'CloudBuild']